using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using OfficeOpenXml;
namespace ShortPay {
static class GuardTests {
 static int count;static void Check(bool condition,string message){count++;if(!condition)throw new Exception("GUARD TEST: "+message);}
 public static void Run(List<Job> jobs,string folder){
  int one=jobs.FindIndex(x=>x.name.Contains("당직")&&x.name.Contains("1인")),two=jobs.FindIndex(x=>x.name.Contains("당직")&&x.name.Contains("2인"));
  var r=new Record{Name="당직 검증",OriginalWorker="원근로자",Reason="연차",Start=new DateTime(2026,4,6),End=new DateTime(2026,4,12),JobIndex=two,Hours=8.5m,WeekendHours=12,MonthlyBase=1477550,Meal=100000,NightDays=3,PublicHolidayDays=1};foreach(int day in new[]{6,8,10,12})r.Days["2026-04-"+day.ToString("00")]=1;
  var z=Engine.Calculate(r,jobs[two]);Check(z.Ready&&z.WorkHours==37.5m&&z.HolidayHours==0&&z.MonthlyHours==144,"two-person mixed weekdays/weekend, no weekly holiday");Check(z.Hourly==10955.21m&&z.BasePay==410820&&z.NightPay==24640&&z.PublicHolidayPay==30780&&z.Gross==466240,"independent expected two-person amount");
  var educational=Engine.Parse<Record>(Engine.Json(r));educational.Start=r.Start;educational.End=r.End;educational.MonthlyBase=1423460;educational.Meal=75000;educational.Minimum=10030;educational.PublicHolidayDays=0;var prior=Engine.Calculate(educational,jobs[two]);Check(prior.Hourly==10405.98m&&prior.BasePay==390220&&prior.NightPay==23410&&prior.Gross==413630,"attached 2025 HWPX example 37.5 working and 4.5 night hours");
  var shortRecord=new Record{Name="단기 당직",JobIndex=one,Start=new DateTime(2026,9,7),End=new DateTime(2026,9,7),Hours=8.5m,MonthlyBase=2965360,Meal=160000,NightDays=1};Engine.Fill(shortRecord);var shortResult=Engine.Calculate(shortRecord,jobs[one]);Check(shortResult.Hourly==10320&&shortResult.MonthlyHours==289&&shortResult.BasePay==87720&&shortResult.NightPay==7740&&shortResult.Gross==95460,"one-day guard minimum wage and 50 percent night premium");
  var full=new Record{Name="1인 당직",JobIndex=one,Start=new DateTime(2026,9,7),End=new DateTime(2026,9,13),Hours=8.5m,WeekendHours=12,MonthlyBase=2965360,Meal=160000};for(var d=full.Start;d<=full.End;d=d.AddDays(1))full.Days[Engine.Key(d)]=1;var fullResult=Engine.Calculate(full,jobs[one]);Check(fullResult.Ready&&fullResult.WorkHours==66.5m&&fullResult.MonthlyHours==289&&fullResult.HolidayHours==0,"one-person 66.5-hour week allowed under attached guard basis");
  var dir=Path.Combine(folder,"guard-exports");Directory.CreateDirectory(dir);var options=new ExportOptions{Year=2026,Month=4,Recipient="가01",Manager="담당자"};r.Institution="예시학교";r.Account="001-00001";r.Employment=false;r.EmploymentExclusionReason="적용 제외 사유 검증";z=Engine.Calculate(r,jobs[two]);Check(z.Employment==0&&z.Net==z.Gross,"employment exemption removes deduction");
  foreach(string kind in new[]{"임금산정표","급여명세서","인건비 신청내역"}){string file=Path.Combine(dir,kind+".xlsx");ExcelReports.Save(file,kind,r,jobs[two],z,options);using(var pkg=new ExcelPackage(new FileInfo(file))){var sheet=pkg.Workbook.Worksheets.First();string cell=kind=="임금산정표"?"G26":kind=="급여명세서"?"F23":"AR14";Check(Convert.ToDecimal(sheet.Cells[cell].Value)==z.Net,"guard workbook reconciles "+kind);if(kind=="인건비 신청내역")Check(sheet.Cells["AH14"].Text=="O"&&sheet.Cells["AP14"].Text==r.EmploymentExclusionReason&&Convert.ToDecimal(sheet.Cells["AD14"].Value)==4&&Convert.ToDecimal(sheet.Cells["AE14"].Value)==30,"exemption and real night hours in dedicated request cells");}}
  foreach(string kind in new[]{"임금산정표","급여명세서"}){string file=Path.Combine(dir,kind+".pdf");PdfReports.Save(file,kind,r,jobs[two],z,options);Check(File.ReadAllBytes(file).Take(5).SequenceEqual(System.Text.Encoding.ASCII.GetBytes("%PDF-")),"generated PDF signature "+kind);}
  var dense=Engine.Parse<Record>(Engine.Json(full));dense.Start=full.Start;dense.End=full.Start.AddDays(22);dense.OriginalWorker="원근로자";dense.Reason="휴직";dense.Institution="전체 항목 예시학교";dense.Within=1.25m;dense.Overtime=2.5m;dense.ExtraPay=35000;dense.NightDays=12;dense.PublicHolidayDays=2;dense.Food=20000;dense.Tax=1500;dense.LocalTax=150;dense.Health=30000;dense.Care=3500;dense.Pension=40000;for(var d=dense.Start;d<=dense.End;d=d.AddDays(1))dense.Days[Engine.Key(d)]=1;var denseResult=Engine.Calculate(dense,jobs[one]);Check(PayrollItems.Pay(dense,denseResult).Sum(x=>x.Amount)==denseResult.Gross&&PayrollItems.Deduct(dense,denseResult).Sum(x=>x.Amount)==denseResult.Deductions,"all displayed nonzero items reconcile with totals");foreach(string kind in new[]{"임금산정표","급여명세서","인건비 신청내역"})ExcelReports.Save(Path.Combine(dir,"전체항목_"+kind+".xlsx"),kind,dense,jobs[one],denseResult,options);foreach(string kind in new[]{"임금산정표","급여명세서"})PdfReports.Save(Path.Combine(dir,"전체항목_"+kind+".pdf"),kind,dense,jobs[one],denseResult,options);
  shortRecord.OriginalWorker="원근로자";shortRecord.Reason="연차";shortRecord.Institution="예시학교";ExcelReports.Save(Path.Combine(dir,"15시간미만_신청서.xlsx"),"인건비 신청내역",shortRecord,jobs[one],shortResult,new ExportOptions{Year=2026,Month=9});Check(File.Exists(Path.Combine(dir,"15시간미만_신청서.xlsx")),"under-fifteen guard request matches minimum wage");
  string saved=Path.Combine(dir,"guard.stpay");Engine.Save(saved,r);var restored=Engine.Load(saved);Check(restored.JobIndex==two&&restored.WeekendHours==12&&restored.NightDays==3&&!restored.Employment&&restored.EmploymentExclusionReason==r.EmploymentExclusionReason,"new contract/exemption fields round trip");
  foreach(int oldIndex in new[]{11,12,13,21,22,23}){var legacy=new Record{Version=3,JobIndex=oldIndex};Engine.Save(saved,legacy);var migrated=Engine.Load(saved);Check(migrated.Version==4&&migrated.JobIndex==(oldIndex==12?11:oldIndex>12?oldIndex-1:oldIndex),"legacy job index migration "+oldIndex);}
  r.NightDays=5;bool blocked=false;try{ExcelReports.Save(Path.Combine(dir,"invalid.xlsx"),"급여명세서",r,jobs[two],Engine.Calculate(r,jobs[two]),options);}catch(InvalidOperationException){blocked=true;}Check(blocked&&!File.Exists(Path.Combine(dir,"invalid.xlsx")),"premium days greater than attendance blocked");
  File.WriteAllText(Path.Combine(folder,"guard-tests.txt"),"PASS "+count+" guard, migration, exemption and PDF checks");
 }
}
public partial class MainForm {
 void ExerciseGuardUI(string folder){
  var notifications=new List<string>();OutputMessage=notifications.Add;openGenerated.Checked=false;
  r=new Record{Name="당직 예시",OriginalWorker="김담당",Reason="연차 대체",Institution="예시학교",Start=new DateTime(2026,9,7),End=new DateTime(2026,9,13)};Engine.Fill(r);LoadUI();RefreshAll();job.SelectedIndex=jobs.FindIndex(x=>x.name.Contains("당직")&&x.name.Contains("2인"));AssertUI(hours.Value==8.5m&&hours.Maximum==24&&weekendField.Visible==false,"guard fields configured while contract page hidden");
  tabs.SelectedIndex=0;Show();AssertUI(weekendField.Visible&&guardFields.Visible,"guard contract fields visible");AssertUI(unmannedSaturday.Checked&&!unmannedSunday.Checked&&r.Days.Count==4,"guard switch creates alternating schedule");unmannedSunday.Checked=true;AssertUI(!unmannedSaturday.Checked&&unmannedSunday.Checked&&!r.Days.ContainsKey("2026-09-13"),"Sunday security excludes duty without shifting cycle");unmannedSunday.Checked=false;AssertUI(unmannedSunday.Checked&&!unmannedSaturday.Checked,"security day cannot be empty");unmannedSaturday.Checked=true;AssertUI(r.Days.Count==4,"Saturday security restores schedule");Set("nightDays",2);Set("publicDays",1);CaptureScreen(Path.Combine(folder,"guard-contract.png"));
  tabs.SelectedIndex=2;employmentExcluded.Checked=true;employmentReason.Text="적용 제외 사유 확인";AssertUI(result.Employment==0&&employmentReason.Enabled,"employment exclusion controls recalculate");loading=true;employmentReason.Text="";loading=false;CaptureScreen(Path.Combine(folder,"guard-money.png"));loading=true;employmentReason.Text=r.EmploymentExclusionReason;loading=false;tabs.SelectedIndex=3;CaptureScreen(Path.Combine(folder,"guard-output.png"));
  foreach(string kind in new[]{"임금산정표","급여명세서"}){string file=CreateDocument(kind,true);AssertUI(File.Exists(file)&&file.EndsWith(".pdf"),"PDF routes to configured document folder");}
  employmentExcluded.Checked=false;foreach(string key in new[]{"food","health","care","pension","tax","local","extra"})Set(key,1000);Set("within",1);Set("overtime",1);tabs.SelectedIndex=3;CaptureScreen(Path.Combine(folder,"all-items-output.png"));
  tabs.SelectedIndex=0;end.Value=start.Value;AssertUI(!numbers["meal"].Enabled&&numbers["meal"].Text==""&&!numbers["allowance"].Enabled,"under fifteen shows blank excluded allowance inputs");end.Value=start.Value.AddDays(6);AssertUI(numbers["meal"].Enabled&&numbers["meal"].Value==100000,"eligible allowance restored after period change");
  job.SelectedIndex=jobs.FindIndex(x=>x.name=="조리실무사");AssertUI(!weekendField.Visible&&!guardFields.Visible&&hours.Maximum==8&&r.NightDays==0,"ordinary job restores ordinary controls");dirty=false;
 }
}
}
